### ISSUE TITLE
LetterToSound: static initializer exceeds 65535 byte limit

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/rita4j#10]
for LetterToSound.java

![Screenshot 2019-12-03 at 1 07 33 PM](https://user-images.githubusercontent.com/4047303/70022138-12bc5480-15ce-11ea-8d49-551d4060fee2.png)

**Comment by dhowe** [comment]
You can just break it into two arrays, RULES1 and RULES2.
Then use the method below (untested) to combine them into RULES, as follows:

```
  public static String[] RULES = combine(RULES1, RULES2);

  private static String[] combine(String[] a, String[] b){
        String[] result = new String[a.length + b.length];
        System.arraycopy(a, 0, result, 0, a.length);
        System.arraycopy(b, 0, result, a.length, b.length);
        return result;
    }
```

**Comment by kennyviperhk** [comment]
I break into 2 array RULES1, RULES2, still had the exceeding warnings. But if I delete the RULES2, warning is gone. I tried break into 4 arrays as well, deleting 2 and the warning is gone. So is there file size/character limit to as well?

**Comment by dhowe** [comment]
'Constant arrays are initialized in java bytecode by loading each value from the constant pool and assigning it to the corresponding array index. This takes several bytes of code per array element. The size of a jvm method is limited to 65535 bytes since its length is stored in the class file using a 16 bit number.'

**Comment by kennyviperhk** [comment]
so we need to break into 2 files for LTS, and access one by one?

**Comment by dhowe** [comment]
is this resolved? if so, pls close

**Comment by cqx931** [comment]
No the whole section is commented out.

**Comment by dhowe** [comment]
Ok, I will have a look

**Comment by dhowe** [comment]
done
