### ISSUE TITLE
Match tests with rita2js

### ISSUE THREAD

**Issue by cqx931** [dhowe/rita4j#18]
- [x] riscript-tests.js 61 (priority)
- [x] analyzer-tests.js 7 
- [x] conjugator-tests.js 4
- [x] grammar-tests.js 15
- [x] lexicon-tests.js 25
- [x] markov-tests.js 25
- [x] rita-tests.js 6
- [x] tagger-tests.js 14
- [x] tokenizer-tests.js 3

Total: 160

**Comment by dhowe** [comment]
nice - as we check these off, lets make sure the exact count of tests matches between js/java, or if not leave a note as to why

**Comment by cqx931** [comment]
https://github.com/dhowe/rita2js/blob/master/test/lexicon-tests.js#L57
How are we going to support customized dictionary in java? 
Because the dictionary is protected, I can't directly access the dictionary in java as how it is done in js:  `RiTa.lexicon().data = {}`, is that going to be implemented in java as a custom function in the lexicon class?

**Comment by dhowe** [comment]
can we make the dictionary public? also [see this comment](https://github.com/dhowe/RiTa/issues/589#issuecomment-630245876) for how it works now

**Comment by cqx931** [comment]
@dhowe we could,  just not sure which one is the best practice here. If we make it public, it will be a more similar match to the js version.
But as you mentioned in the comment, our previous approach has been a custom addWord() function.

**Comment by dhowe** [comment]
Let's match js

**Comment by cqx931** [comment]
Finished riscript-tests.js except for the new two tickets: #26, #27.

**Comment by cqx931** [comment]
Making a PR for recent changes in JUnit environment: https://github.com/dhowe/rita2/pull/28

**Comment by cqx931** [comment]
Done. Please check: https://github.com/dhowe/rita2/pull/32

**Comment by dhowe** [comment]
> Done. Please check: #32 

Unless I'm missing something Markov and Grammar tests haven't been ported over from current ritajs

**Comment by cqx931** [comment]
Redone Markov and Grammar tests at here: https://github.com/dhowe/rita2/tree/updateTests
There are still a few lines marked as TODO but the majority of the test cases are done.

**Comment by dhowe** [comment]
Merged into master
