### ISSUE TITLE
Support for Android

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita4j#24]
We need to verify the library can be used on Android (with and without processing) -- I'm not sure the best way to do this with junit/maven... we may need a separate way to test

**Comment by cqx931** [comment]
This SO ticket should be a very similar situation as ours(without processing): https://stackoverflow.com/questions/11048805/maven-plugin-for-checking-api-compliance-with-android

**Comment by dhowe** [comment]
this means that its compatible with android, not that anything will run correctly, so we should use this but we ALSO need to include a real android test in our release testing (#37)
