### ISSUE TITLE
RiTa.addTransform() in java

### ISSUE THREAD

**Issue by cqx931** [dhowe/rita4j#26]
I'm working on the test cases for RiTa.addTransform() and I'm not sure how can I translate this from js to java
`(s) => s || 'B'`
 https://github.com/dhowe/rita2js/blob/master/test/riscript-tests.js#L580
Is this translatable in java? Shouldn't input value always match with the predefined type?

I can also use another function here, as the test case is testing addTransform() in context.
`Function<String, String> func = (x) -> {return "A";};`

**Comment by dhowe** [comment]
`let ctx = { 'capB': (s) => s || 'B' };`

This is just a mapping (a Map) from 'capB' to a Function that takes a String and returns it if it is not null, else returns "B".
So, something like:

```
// same function as above
Function<String, String> fun = s -> ( s != null ? s : "B");

// return a Map with "capB" as key, 'fun' as value
Map<String, Object> ctx = Util.opts("capB", fun);
```
so,
```
Function<String, String> fun = s -> ( s != null ? s : "B");
RiTa.evaluate(".capB()", Util.opts("capB", fun), Util.opts("trace", true));
```

**Comment by cqx931** [comment]
Thanks!
