### ISSUE TITLE
Questions on assertThrows()

### ISSUE THREAD

**Issue by cqx931** [dhowe/rita4j#27]
When I'm working on RiScriptTests.java I was trying to find the best way to translate the following in js:
`expect(() => RiTa.evaluate('{$a<} foo', { a: 2 }, { silent: 1 })).to.throw();`

For some of the throw error tests I have used the following syntax that is available in JUnit 4.12:
```
@Test(expected = RiTaException.class)
	public void testBadConditionals() {
		Map<String, Object> ctx = opts();
		ctx.put("a", 2);
		RiTa.evaluate("{$a<} foo", ctx, opts("silent", true));
	}
```

But I'm not sure what's the best method I could use for multiple throw errors asserts within one test case.
Example: https://github.com/cqx931/rita2/blob/master/src/test/java/rita/test/RiScriptTests.java#L633

We are now using JUnit 4.12 and JUnit 5 Jupiter assertions API introduces the assertThrows method for asserting exceptions that seem to be very easy to use. Could we switch to JUnit 5?

Reference:
https://www.baeldung.com/junit-assert-exception

**Comment by dhowe** [comment]
JUnit 5 is fine with me (assuming it doesn't cause any other problems). You can update the dependency in pom.xml

**Comment by cqx931** [comment]
Switched to JUnit 5

**Comment by dhowe** [comment]
If we run into problems we can also revert to how it was done in RiTa v1 using org.junit.Assert.fail()

See RiTa/java/rita/test/RiTaTest.java::1847
