### ISSUE TITLE
closeTo() equivalent  in java

### ISSUE THREAD

**Issue by cqx931** [dhowe/rita4j#29]
I'm trying to find the equivalent for `expect(1.5).to.be.closeTo(1, 0.5);` in java.
From a quick research I found a good match implemented in Harmcrest: http://hamcrest.org/JavaHamcrest/javadoc/1.3/org/hamcrest/number/IsCloseTo.html

Could we add Harmcrest as another library for the JUnit test in java?

**Comment by dhowe** [comment]
assertEquals(float,float,float)
