### ISSUE TITLE
RiTa v2 website

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita4j#31]
Migrate new website code from https://github.com/dhowe/RiTa to https://github.com/dhowe/RiTaWeb

See https://github.com/dhowe/RiTa/issues/561

**Comment by cqx931** [comment]
Done: https://github.com/dhowe/RiTaWeb/pull/1

**Comment by cqx931** [comment]
can this be closed or is does it still need some fine-tweaking?@dhowe

**Comment by dhowe** [comment]
I will add new tickets there: see https://github.com/dhowe/RiTaWeb/issues/2
