### ISSUE TITLE
What's the best way to implement Node objects in java?(for markov)

### ISSUE THREAD

**Issue by cqx931** [dhowe/rita4j#33]
https://github.com/dhowe/rita2js/blob/master/src/markov.js#L7

Asking because of test cases such as [this one](https://github.com/dhowe/rita2js/blob/master/test/markov-tests.js#L486)

This one?
https://docs.oracle.com/javase/8/docs/api/org/w3c/dom/Node.html

**Comment by dhowe** [comment]
Its our [own class](https://github.com/dhowe/rita2js/blob/master/src/markov.js#L275) defined inside Markov

**Comment by cqx931** [comment]
I see, thanks!
