### ISSUE TITLE
Inline posTags() return type

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/rita4j#4]
in rita-script
normally posTags will return String Array
` RiTa.posTags("He outnumbers us") ===> ["prp", "vbz", "prp"] `

and for { inline: true } will return String
` RiTa.posTags("asdfaasd", { inline: true }) ===> "asdfaasd/nn" `

are we doing the same in RiTa Java? or we should align both to return String Array?

**Comment by dhowe** [comment]
Keep both functions in both:

RiTa.posTags
RITa.posTagsInline
