### ISSUE TITLE
Finish Java classes and tests

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita4j#42]
- [x] Tokenizer
- [ ] Markov (completions(), probability(), probabilities())
- [ ] Grammar (on hold)

For each class above, do the following:
1. make sure tests are in sync with JS
2. implement functions to make tests pass
3. ask questions about the best way to do things in Java
4. make sure code compiles and is correctly formatted (using [this formatter](https://rednoise.org/ftp/formatter.xml))

**Comment by dhowe** [comment]
Good start. A few things:
- [ ] Pre-compile ALL regexes as constants: `private static final Pattern BLAH_RE = Pattern.compile("blah");`
- [ ] Add tests for RiTa.untokenize(String[], String) and RiTa.tokenize(String, String)
- [x] Add more tests to testTokenizeAndBack() 
- [ ] Fix #46 (low priority for now)

**Comment by Real-John-Cheung** [comment]
waiting for Riscript

**Comment by dhowe** [comment]
@Real-John-Cheung  riscript is ready
