### ISSUE TITLE
Problem in Riscript - transform

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/rita4j#54]
is add to knownIssues by #53 
transform will fail when assign and choice is use together, e.g
`$a=a\n($a).toUpperCase()` and `$a=a\n($a | $a).toUpperCase()`

this problem cause many fails in Grammar and Riscript

seems that with choice, transform is wrongly added before the choice is done
it might be some problem in the tree...
@dhowe maybe you will want to look into this

more info in the code comment in KnownIssues

**Comment by dhowe** [comment]
thanks -- I'm aware of the issue and working on it in a separate branch, so as I mentioned, some of the grammar tests will need to wait until I can find some more time to work with it

**Comment by dhowe** [comment]
should be fixed -- please verify and close if ok

**Comment by Real-John-Cheung** [comment]
This problem is fixed
but seems that there are still problems of 1. dealing with "`\n`" 2. dealing with rules started with number (e.g. `$1foo`)
I will open another ticket for that

**Comment by Real-John-Cheung** [comment]
@dhowe it seems that there is still issue related to choice in some cases....
for example `($a b).pluralize()\n$a=(a | a)` in which the transform is parsed alone and do not thing
I am sorry that I didn't find out this kind of use and include it before, I have add it in KnownIssues with #60
