### ISSUE TITLE
Remaining Problems in RiScript

### ISSUE THREAD

**Issue by Real-John-Cheung** [dhowe/rita4j#58]
- [x] dealing with line breaks like `\n`
- [x] dealing with rules starting with number, like `$1foo`
- [x] throw on bad choice
- [ ] dealing with Rita function transform e.g. using `RiTa.env()` in the input -> on hold
- [x] Custom transform using `RiTa.addTransform()`
- [x] dealing with `norep()`
- [x] `rseq()` -> the dont repeat part only
- [x] `seq()`
- [x] using assignment with symbol in context refer to #64  (grammar-tests)

**Comment by dhowe** [comment]
@Real-John-Cheung can you update this ticket pls
