### ISSUE TITLE
kwic parameters

### ISSUE THREAD

**Issue by kennyviperhk** [dhowe/rita4j#7]
in rita.js
```
kwic: function(word, numWords) {
..
}
```

int Rita
```
String[] kwic(String text, String word, Map<String, Object> opts)
or
String[] kwic(String text, int numWords, Map<String, Object> opts)
```

?

**Comment by dhowe** [comment]
I don't think they are any 'options' for this function, so all we need is:

`String[] kwic(String text, String word)`

**Comment by kennyviperhk** [comment]
in js the second parameter seems to be number?

and what is value.indexes?

```
  kwic(word, numWords) {
    if (!this.model) throw Error('Call concordance() first');
    let value = this._lookup(word),
      result = [];
    if (value) {
      let idxs = value.indexes;
      for (let i = 0; i < idxs.length; i++) {
        let sub = this.words.slice(Math.max(0, idxs[i] - numWords),
          Math.min(this.words.length, idxs[i] + numWords + 1));

        if (i < 1 || (idxs[i] - idxs[i - 1]) > numWords) {
          result.push(RiTa.untokenize(sub));
        }
      }
    }
    return result;
  }
```

**Comment by dhowe** [comment]
> in js the second parameter seems to be number?

yes, the number of words surrounding the target word

> and what is value.indexes?

_lookup returns an object with three properties: word, key, and indexes. Indexes stores all the indexes in the word array where that specific word appears:

![Screen Shot 2019-12-03 at 5 16 15 PM](https://user-images.githubusercontent.com/737638/70037431-83289d00-15f1-11ea-8042-80811a7983b4.png)
