### ISSUE TITLE
Add concorder() and kwic() test functions

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita4j#88]

**Comment by Real-John-Cheung** [comment]
@dhowe hmm. there are tests for concordance() already, but for kwic() seems that in Java this API is blocked (it always return null), see https://github.com/dhowe/rita2/blob/1f20738306d2f0b5dbaa2bbc70b93919f8acbb2e/src/main/java/rita/Concorder.java#L58

**Comment by dhowe** [comment]
Ok, it is there now. Please make sure the tests are in sync between java/js for RiTa.kwic() and RiTa.concondance()

**Comment by dhowe** [comment]
coverage still low
![image](https://user-images.githubusercontent.com/737638/101979663-e5eb5480-3c99-11eb-89b5-004b462a5901.png)

**Comment by dhowe** [comment]
please get (at least) >= 90%
