### ISSUE TITLE
Markov Workbench 

### ISSUE THREAD

**Issue by dhowe** [dhowe/rita4j#9]
Should be a single .html page with (jquery is fine):
1. 1 div/text-area for input text
1. 1 div (no text-area needed) for output
1. 2 buttons (one for 'load', one for 'execute')
1. One knob called 'temperature' (0-1, default value is 0)
1. One knob called 'speed' (0-1, default value is .5)
1. One pulldown or knob called 'N' (1-5, default value is 3, integers only)

The 'input' text area should have a vertical slider if text is longer than window and should wrap at the width. The output div should auto-wrap at the width of the window. New lines will appear at top (don't worry about this for now)

- ‘load’ can handle local-files only for now (should bring up the finder/explorer)
- ‘execute’ should be disabled if there is no text in the input text-area (top)

**Comment by kennyviperhk** [comment]
https://github.com/kennyviperhk/Markov-Workbench

**Comment by kennyviperhk** [comment]
<img width="1388" alt="Screenshot 2019-11-28 at 6 51 06 PM" src="https://user-images.githubusercontent.com/4047303/69800362-1045ad80-1210-11ea-9b4f-03a850269867.png">

**Comment by dhowe** [comment]
good for now
